remote_theme: pages-themes/minimal@v0.2.0

title: Yuejiao Su's Homepage
description: Welcome to my homepage!
logo: syj.jpg

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
